API_ENDPOINTS = {
    "login": "/api/v1/get_token",
    "signup": "/api/v1/signup",
    "get_all_services": "/api/v1/products/get_all_services",
    "get_categories": "/api/v1/products/get_categories",
    "get_services_by_category": "/api/v1/products/get_services",
    "create_order": "/api/v1/create_order",
    "pay_order": "/api/v1/pay_order",
    "check_balance": "/api/v1/check_balance",
    "calculate_steam_amount": "/api/v1/steam/get_amount",
    "get_steam_currency_rate": "/api/v1/steam/get_currency_rate",
    "get_user_info": "/api/v1/user",
    "calculate_steam_gift": "/api/v1/steam_gift/calculate",
    "create_steam_gift_order": "/api/v1/steam_gift/create_order",
    "pay_steam_gift_order": "/api/v1/steam_gift/pay_order",
    "get_order_info": "/api/v1/order_info",
    "get_steam_package_price": "/api/v1/steam_gift/get_price",
    "add_ip_to_whitelist": "/api/v1/ip-whitelist/add",
    "remove_ip_from_whitelist": "/api/v1/ip-whitelist/remove",
    "list_whitelist_ips": "/api/v1/ip-whitelist/list",
}